resources:
  traefik-deployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${namespace}
        name: ${traefik.service-name}
        labels:
          app: ${traefik.service-name}
      spec:
        replicas: ${traefik.replicas-nb}
        selector:
          matchLabels:
            app: ${traefik.service-name}
        template:
          metadata:
            labels:
              app: ${traefik.service-name}
          spec:
            serviceAccountName: ${traefik.service-account-name}
            containers:
              - name: traefik
                image: ${traefik.image}
                args:
                  - --providers.kubernetesingress=true
                  - --providers.kubernetesingress.allowEmptyServices=true
                  - --providers.kubernetesingress.namespaces=${namespace}
                  # logging
                  - --log.level=${traefik.logging.level}
                  - --log.format=${traefik.logging.format}
                  - --accesslog
                  # entrypoints
                  - --entryPoints.${traefik.ports.http.name}.address=:${traefik.ports.http.targetPort}
