resources:
  traefik-service:
    type: kubernetes:core/v1:Service
    properties:
      metadata:
        namespace: ${namespace}
        name: ${traefik.service-name}
        
      spec: 
        ports:
          - protocol: TCP
            port: ${traefik.ports.http.port}
            targetPort: ${traefik.ports.http.targetPort}
            name: ${traefik.ports.http.name}
        selector:
          app: ${traefik.service-name}
        type: LoadBalancer
