resources:
  traefik-rbac-cluster-role-binding:
    type: kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding
    properties:
      metadata:
        name: ${traefik.role-binding-name}
        namespace: ${namespace}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: ${traefik.role-name}
      subjects:
        - kind: ServiceAccount
          name: ${traefik.service-account-name}
          namespace: ${namespace}
