resources:
  whoami-deployment:
    type: kubernetes:apps/v1:Deployment
    properties:
      metadata:
        namespace: ${namespace}
        name: ${whoami.service-name}
        labels:
          app: ${whoami.service-name}
      
      spec:
        replicas: ${whoami.replicas-nb}
        selector:
          matchLabels:
            app: ${whoami.service-name}
        template:
          metadata:
            labels:
              app: ${whoami.service-name}
          spec:
            containers:
              - name: whoami
                image: ${whoami.image}
                ports:
                  - name: ${whoami.ports.http.name}
                    containerPort: ${whoami.ports.http.targetPort}
