resources:
  whoami-http-ingress:
    type: kubernetes:networking.k8s.io/v1:Ingress
    properties:
      metadata:
        namespace: ${namespace}
        name: whoami-http-ingress
        annotations:
#          traefik.ingress.kubernetes.io/router.entrypoints: ${traefik.ports.http.name}
          pulumi.com/skipAwait: "true"

      spec:
        rules:
          - host: ${urls.prefix}whoami${urls.suffix}.${domain}
            http:
              paths:
                - path: /notls
                  pathType: Exact
                  backend:
                    service:
                      name: ${whoami.service-name}
                      port:
                        number: ${whoami.ports.http.targetPort}
